# configs/transvod_ships.yaml

DATASETS:
  TRAIN: ["ships_train"]
  TEST: ["ships_val"]

MODEL:
  WEIGHTS: "D:/TransVOD/TransVOD-master/exps/our_models/exps_multi/checkpoint.pth"
  MASK_ON: False

INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 768

SOLVER:
  BASE_LR: 0.00005
  IMS_PER_BATCH: 1
  STEPS: (500, 750)
  MAX_ITER: 1000

TEST:
  EVAL_PERIOD: 500